### ISSUE TITLE
Problem getting robot joint state

### ISSUE THREAD

**Issue by anefg** [moveit/moveit_core#96] opened 2013-10-23 14:11 UTC
Every time I try to recover the joint states of my simulated arm using the method getVariableValues() I always get the same joint state position: 0.0, although the joints are moved.

I have loaded the model of the robot and populated the RobotState structure. I have also created an instance of MoveGroup object to be able to move it but it doesn't work.

The code that I'm executing is:

/\* Load the robot model */
robot_model_loader::RobotModelLoader robot_model_loader("robot_description");

/\* Get a shared pointer to the model */
robot_model::RobotModelPtr kinematic_model = robot_model_loader.getModel();

/\* WORKING WITH THE KINEMATIC STATE /
/ Create a kinematic state - this represents the configuration for the robot represented by kinematic_model */
robot_state::RobotStatePtr kinematic_state(new robot_state::RobotState(kinematic_model));

/\* Get the configuration for the joints robotnik arm_/
robot_state::JointStateGroup_ joint_state_group = kinematic_state->getJointStateGroup("robotnik_arm");

/\* Get the joint states for the right arm*/
std::vector joint_values;
joint_state_group->getVariableValues(joint_values);

Thanks

**Comment by isucan** [comment] 2013-10-23 17:13
This is a duplicate of #94 
Please see the suggestions there. In particular, please also use 
http://moveit.ros.org/doxygen/classplanning__scene__monitor_1_1PlanningSceneMonitor.html

**Closed as completed by isucan** 2013-10-23 17:13 UTC
